version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongo-service
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: service_manager
    volumes:
      - mongo-data:/data/db
      - ./init/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - app-network

  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongo-service:27017/service_manager?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  go-client:
    build:
      context: ./go-client
      dockerfile: Dockerfile
    container_name: go-client
    depends_on:
      - backend-app
      - mongodb
    networks:
      - app-network
    command: ["sleep", "infinity"]

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "4200:80"
    depends_on:
      - backend-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
