spring:
#  datasource:
#    url: jdbc:postgresql://postgres:5432/flights-db
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#appUserName: user
#password: password
#
  data:
    mongodb:
      uri: mongodb://localhost:27017/service_manager_db

management:
  endpoints:
    web:
      exposure:
        include: health,info
#  endpoint:
#    health:
#      show-details: always  # or "when-authorized"