
spring:
  data:
    mongodb:
      uri: mongodb://admin:password@mongo-service:27017/service_manager?authSource=admin



server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG

