spring:
  data:
    mongodb:
      uri: mongodb://admin:password@mongo-service:27017/service_manager_dev?authSource=admin



server:
  port: 8080

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    com.yourpackage: DEBUG  # Replace with your actual base package
#
#app:
#  cache:
#    enabled: true
#    maxSize: 1000





#spring:
#  datasource:
#    url: jdbc:postgresql://postgres:5432/flights-db
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#
#appUserName: user
#password: password
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#  endpoint:
#    health:
#      show-details: always  # or "when-authorized"
