openapi: 3.0.3
info:
  title: Service API
  version: 1.0.0
  description: REST API for managing Service entities

paths:
  /v1/services:
    post:
      summary: Create a new Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      responses:
        '201':
          description: Service created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseServiceDto'

  /v1/services/{id}:
    get:
      summary: Fetch a Service by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Service fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseServiceDto'
        '404':
          description: Service not found

    put:
      summary: Update a Service by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      responses:
        '200':
          description: Service updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseServiceDto'
        '404':
          description: Service not found

components:
  schemas:
    Service:
      type: object
      properties:
        # Replace or extend with your actual Service model fields
        id:
          type: string
        name:
          type: string
        description:
          type: string

    ServiceDto:
      type: object
      properties:
        # Replace or extend with your actual ServiceDto fields
        id:
          type: string
        name:
          type: string
        status:
          type: string

    ApiResponseServiceDto:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/ServiceDto'
